[colors.bright]
black = "#585b70"
blue = "#89b4fa"
cyan = "#94e2d5"
green = "#a6e3a1"
magenta = "#f5c2e7"
red = "#f38ba8"
white = "#a6adc8"
yellow = "#f9e2af"

[colors.normal]
black = "#45475a"
blue = "#89b4fa"
cyan = "#94e2d5"
green = "#a6e3a1"
magenta = "#f5c2e7"
red = "#f38ba8"
white = "#a6adc8"
yellow = "#f9e2af"

[colors.primary]
background = "#1e1e2e"
bright_foreground = "#24273a"
dim_foreground = "#303446"
foreground = "#cdd6f4"

[colors.cursor]
cursor = "CellForeground"
text = "CellBackground"

[font]
size = 16

[font.normal]
family = "Monaspace Neon"
style = "Regular"

[font.bold]
family = "Monaspace Neon"
style = "Bold"

[font.italic]
family = "Monaspace Neon"
style = "Italic"

[hints]
alphabet = "jfkdls;ahgurieowpq"

[[hints.enabled]]
command = "open"
post_processing = true
regex = '(((?:[.\w\-@~]+)?(?:/[.\w\-@]+)+)|((https?://|git@|git://|ssh://|ftp://|file:///)\S+)|(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})|([A-f0-9:]+:+[A-f0-9:]+[%\w\d])+)'

[hints.enabled.binding]
key = "X"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = false
mods = "None"

[[hints.enabled]]
action = "Copy"
post_processing = true
regex = '(((?:[.\w\-@~]+)?(?:/[.\w\-@]+)+)|((https?://|git@|git://|ssh://|ftp://|file:///)\S+)|(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})|([A-f0-9:]+:+[A-f0-9:]+[%\w\d])+)'

[hints.enabled.binding]
key = "C"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "None"

[window]
opacity = 1.0
blur = true

[window.padding]
x = 10
y = 10
